# Site settings
title:          William Granados
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/blog"
url:            "https://wlgranados.github.io"

# Author
author:
  name:         William Granados
  url:          https://wgma.ca
  email:        me@wgma00.me

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
